### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by benjackwhite** [Jpadilla1/react-native-ios-charts#1]
Great work on this so far! Would like to start from your base and add some things (support for animations etc) but to do so it would be good to have a license sorted. MIT is my goto unless you have other thoughts?

**Comment by Jpadilla1** [comment]
@benthewhite thank you! I actually started support for animations yesterday and pushed them today, but any help is welcomed! For example, right now I am trying to make common config options work in a parent class so other charts can have them out of the box in swift, but I keep running into an error when inheriting (Line, Bar)ChartDataProvider... About the license, I think that MIT is the way to go!
