### ISSUE TITLE
Android support?

### ISSUE THREAD

**Issue by lynndylanhurley** [Jpadilla1/react-native-ios-charts#10]
I was just about to write a library like this myself. Do you plan on supporting Android?

I'm sure you're aware of this library:
https://github.com/PhilJay/MPAndroidChart

**Comment by Jpadilla1** [comment]
Hey @lynndylanhurley, Mike Monteith started to port the Android library, https://github.com/mikemonteith/react-native-mpchart, a while ago and we have plans to merge both libraries into a single one for both iOS and Android. Doesn't seem that he has updated it for a while now. But Android support is a must to have.

**Comment by lynndylanhurley** [comment]
Thanks @Jpadilla1. Feel free to close this issue, I was just curious.

**Comment by Jpadilla1** [comment]
Awesome!

**Comment by mahlon-gumbs** [comment]
Just an FYI: I've successfully used both this library for iOS and https://github.com/hongyin163/react-native-chart-android for Android in a client's app. With both being based (directly or indirectly) on MPChart, it makes for a fairly uniform look and feel across platforms.

**Comment by Jpadilla1** [comment]
@mahlon-gumbs Happy to hear that :)
