### ISSUE TITLE
array cannot be bridged from Objective-C

### ISSUE THREAD

**Issue by L-Jovi** [Jpadilla1/react-native-ios-charts#11]
when I call `setState()` or `render()` method, below error appear.

```
fatal error: array cannot be bridged from Objective-C
```

![error](https://cloud.githubusercontent.com/assets/7262199/13904252/19188b24-eed5-11e5-90c1-87437da215b1.png)

by the way, it's the awesome project which I need :)

**Comment by Jpadilla1** [comment]
HI @L-Jovi can you post your source code so I can reproduce and the library version? Thank you :)

**Comment by Jpadilla1** [comment]
I added an example using setState on the colors and values https://github.com/Jpadilla1/react-native-ios-charts/blob/master/examples/ChartsExplorer/components/LiveUpdating.js. Let me know if that helps!

**Comment by L-Jovi** [comment]
@Jpadilla1  thanks for your reply and new example, I'll extract relevant code with this issue.

I wonder why the same code work as different behaviour, the error always appear in my origin project, but works well in another pure react native project :(

**version**

```
"react-native-ios-charts": "^0.2.0",
```

```
use_frameworks!

target 'tyrantdb_client_ios' do
  pod 'SwiftyJSON', '~> 2.3'
  pod 'Charts', '~> 2.2'
end
```

**index.ios.js**

```
'use strict';

import React from 'react-native';
import {
  LineChart,
} from 'react-native-ios-charts';
import chartConfig from './chartConfig';

const {
  AppRegistry,
  Component,
  View,
  Text,
} = React;

class Main extends Component {
  constructor(props) {
    super(props);

    this.state = {
      test: 1,
    };
  }

  test() {
    this.setState({
      test: this.state.test + 1,
    });
  }

  render() {
    return (
      <View style={{ flex: 1, marginTop: 64 }}>
        <Text
          style={{ textAlign: 'center' }}
          onPress={this.test.bind(this)}>
          test {this.state.test}
        </Text>
        <LineChart
          style={{ flex: 1, }}
          config={chartConfig}
        />
      </View>
    );
  }
}

AppRegistry.registerComponent('Main', () => Main);
```

**chartConfig.js**

```
'use strict';

module.exports = {
  dataSets: [
    {
      values: [8, 21, 78, 63, 34, 23, 111],
      drawValues: true,
      colors: ['rgb(65, 84, 99)'],
      label: 'yesterday',
      drawCubic: true,
      drawCircles: true,
      circleColors: ['rgb(65, 84, 99)'],
      drawCircleHole: true,
      circleRadius: 3,
      lineWidth: 2,
      drawFilled: true,
      fillColor: ['rgb(65, 84, 99)'],
      fillAlpha: 0.7,
    },
  ],
  backgroundColor: 'transparent',
  labels: ['1', '2', '3', '4', '5', '6', '7'],
  minOffset: 20,
  scaleYEnabled: true,
  legend: {
    textSize: 12
  },
  xAxis: {
    axisLineWidth: 1,
    drawLabels: true,
    position: 'bottom',
    drawGridLines: true,
  },
  leftAxis: {
    customAxisMax: 1,
    customAxisMin: -1,
    labelCount: 8,
    startAtZero: true,
    spaceTop: 0.1,
    spaceBottom: 0.1
  },
  rightAxis: {
    enabled: false,
    drawGridLines: false
  },
  valueFormatter: {
    minimumSignificantDigits: 1,
    type: 'regular',
    maximumDecimalPlaces: 1
  },
  animation: {
    xAxisDuration: 2,
    yAxisDuration: 2,
    easingOption: 'easeInQuart',
  },
};

```

**Comment by L-Jovi** [comment]
@Jpadilla1  I eventually confirm it's react native version cause this issue, I ignore it as first, and then I upgrade to `0.21` from `0.20`, all things back to normal.

**Comment by Jpadilla1** [comment]
@L-Jovi The react-native version was actually irrelevant. It was a bug in my library. With this commit https://github.com/Jpadilla1/react-native-ios-charts/commit/41d63a18ec68c7ef05ae2419c3ddcd1e340f1484 I just tested `0.21`, `0.20`, `0.19` and it worked just fine with your code.

Pushed `0.2.1` to npm aswell.

**Comment by L-Jovi** [comment]
@Jpadilla1  awesome, I think your conclusion is correct.

with `npm install` have a bit issue now.

```
shasum check failed for /var/folders/ym/9kftgsm13435827mg4j0lylr0000gn/T/npm-47917-1c9d5cf5/registry.npmjs.org/react-native-ios-charts/-/react-native-ios-charts-0.2.1.tgz

Expected: 2154746076aad981213da4f2bb1871c3a7f6e959
Actual:   088fb8c797c70abda29f592e042870d771a1a5fb
```

thanks for your patience :)

**Comment by Jpadilla1** [comment]
Strange, I just did a fresh install on a new project and it works just fine. Did you try this?

```
rm -rf node_modules
npm cache clean
npm install
```

**Comment by L-Jovi** [comment]
@Jpadilla1  great, it's correct now 👍

**Comment by Jpadilla1** [comment]
Awesome!
