### ISSUE TITLE
CombinedChart issue

### ISSUE THREAD

**Issue by minggo** [Jpadilla1/react-native-ios-charts#14]
I think the effect of CombinedChart in ChartsExplorer is wrong. [config.barData](https://github.com/Jpadilla1/react-native-ios-charts/blob/master/examples/ChartsExplorer/components/Combined.js#L21) in `Combined.js` is  the same as [config.dataSets](https://github.com/Jpadilla1/react-native-ios-charts/blob/master/examples/ChartsExplorer/components/Bar.js#L20) in `Bar.js`, but their effects of bar are different.

**Comment by Jpadilla1** [comment]
Hi @minggo, I fixed the example in the ChartsExplorer. Thank you for pointing that out! I changed it to only use 1 data set.

Their seems to be a PR for grouped bar chart that hasn't been merged yet in the iOS Charts repo https://github.com/danielgindi/ios-charts/pull/269

**Comment by minggo** [comment]
@Jpadilla1 Thanks.
Yep, this feature is missing on iOS and Android.
