### ISSUE TITLE
axisDependency is missing

### ISSUE THREAD

**Issue by minggo** [Jpadilla1/react-native-ios-charts#16]
It seems that axisDependency property is missing in react native.

**Comment by Jpadilla1** [comment]
Yes, I see if I find sometime to include support for it today.

**Comment by minggo** [comment]
Thanks.

**Comment by Jpadilla1** [comment]
Added support in latest release `0.2.2`. Let me know if it works for you!

**Comment by minggo** [comment]
Thanks, it worked.
