### ISSUE TITLE
A question about CombinedChart

### ISSUE THREAD

**Issue by minggo** [Jpadilla1/react-native-ios-charts#17]
I want to CombinedChart to combine BarChart and CandleStickChart, they have different meaning. BarChart may mean how many people, and CandleStickChart means price. Which mean they have different unit. Because BarChart value is very big[1000 - 10000], and CandleStick value is small[20 - 30].  How can i draw then in the same area? 

Thanks.

**Comment by Jpadilla1** [comment]
I believe that by using the axisDependency prop this should work. Let's say that the leftAxis has the range of [1000 - 10000] and the axisDependency for the BarChart is the left one. The BarChart will be drawn according to that axis. The same with the CandleStickChart with the axisDependency of the right axis.

Currently their is no support for axisDependency in this library to do this, but I'll do my best to include support as soon as possible.

**Comment by minggo** [comment]
Yep, so waiting the axisDependency property. Then i will take a try.

**Comment by Jpadilla1** [comment]
Hi @minggo I jus added support for the axisDependency property. You can check the CombinedChart example in the ChartsExplorer where I use it with the bubble chart with values between 1,000 and 10,000 while having the values of the other charts lower than 100.

https://github.com/Jpadilla1/react-native-ios-charts/blob/master/examples/ChartsExplorer/components/Combined.js
