### ISSUE TITLE
Missing customAxisMin and customAxisMax members in ChartAxisBase.swift

### ISSUE THREAD

**Issue by tehong** [Jpadilla1/react-native-ios-charts#21]
Hi,

I've just installed the react-native-ios-charts based on your instruction but I've encoutered the following iOS compiling errors in the BarLineChartViewBaseExtension.swift:

`
            if json["leftAxis"]["axisMinimum"].isExists() {
                self.leftAxis.customAxisMin = json["leftAxis"]["axisMinimum"].doubleValue;
            }
`

`
            if json["leftAxis"]["axisMaximum"].isExists() {
                self.leftAxis.customAxisMax = json["leftAxis"]["axisMaximum"].doubleValue;
            }
`

The errors are:

"Value of type 'ChartYAxis' has no member 'customAxisMin'

and

"Value of type 'ChartYAxis' has no member 'customAxisMax'

Searching through the pods and I found that in CharAxisBase.swift that there are only these two declarations:

`
    /// Flag indicating that the axis-min value has been customized
    internal var _customAxisMin: Bool = false
`
`
    /// Flag indicating that the axis-max value has been customized
    internal var _customAxisMax: Bool = false
`

It seems that that the customAxisMin and customAxisMax are not declared as public members in your Pods files, not in the ChartAxisBase.swift or the ChartYAxis.swift.

Here is my podfile entries:

pod 'SwiftyJSON', '~> 2.3'
pod 'Charts', '~> 2.2' 

Are you missing some updates to the CocoaPods or am I doing something wrong?

I'm pretty much stuck here and need some helps.

**Comment by Jpadilla1** [comment]
Can you try updating in your pod file to `pod 'Charts', '2.3.3'` and the run `pod install` again? Updated the readme, sorry for the confusion.

**Comment by tehong** [comment]
Analyzing dependencies
[!] Unable to satisfy the following requirements:
- `Charts (= 2.3.3)` required by `Podfile`

Not sure if there is such version.

**Comment by Jpadilla1** [comment]
oops! `2.2.3` sorry...

**Comment by tehong** [comment]
Passed compilation but you need to change your pod instruction to these:

pod 'SwiftyJSON', '~> 2.3'
pod 'Charts', '2.2.3'

There is no SwiftyJson 2.3.

**Comment by Jpadilla1** [comment]
Awesome! Thanks, just updated the readme.
