### ISSUE TITLE
viewportoffset is missing

### ISSUE THREAD

**Issue by minggo** [Jpadilla1/react-native-ios-charts#23]
By using `chart.setViewPortOffsets()` can make a chart full fill the space as mentioned in [this thread](https://github.com/PhilJay/MPAndroidChart/issues/760). But it seems there is not way to do it in `react-native-ios-charts`.

**Comment by minggo** [comment]
I used a CombinedChart(BarChart + CandleStickChart), and i want it to fill the spaces, but now it has padding in top and left as below
<img width="404" alt="screen_shot_2016-04-26_at_9_54_06_pm" src="https://cloud.githubusercontent.com/assets/488203/14820662/2a89f7f2-0bfa-11e6-857f-5c14eceac441.png">

**Comment by minggo** [comment]
@Jpadilla1 Could you please take a look?

**Comment by Jpadilla1** [comment]
Sure, I'll take a look today.

**Comment by Jpadilla1** [comment]
Added support on latest version `0.2.4`.

Example in config:

```
viewport: {
  left: 0,
  top: 0,
  right: 0,
  bottom: 0
}
```

Also added to the Bar Chart in the ChartsExplorer.
