### ISSUE TITLE
blank background after update react-native

### ISSUE THREAD

**Issue by inu1255** [Jpadilla1/react-native-ios-charts#24]
it's blank background what ever I set `backgroundColor`,I just think it's woring with my code,but when I create a new react-native project and use the demo code,it's blank background too. any one meet the same problem?

**Comment by Jpadilla1** [comment]
Hi @inu1255, which version of react-native are you using and can you post some screenshots of this? It might help placing the `backgroundColor` as a style prop instead of placing it in the chart config object.

**Comment by inu1255** [comment]
it's great,thank you,I set style prop of LineChart like this `style={{backgroundColor:"#fff"}}` and it become a white background.

this is the black background,I use the demo code and edit nothing.
![image](https://cloud.githubusercontent.com/assets/5772409/14941784/19afdaac-0fdb-11e6-81b7-af688b75a459.png)
package.json
``` javascript
{
  "name": "Test",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "react": "^0.14.8",
    "react-native": "^0.24.1",
    "react-native-ios-charts": "^0.2.3"
  }
}
```

**Comment by cmouysset** [comment]
Hello.

I'm using React Native 0.25 and when I run the examples I get a blank box where the chart should be displayed. Is anyone else running into this issue?

Thanks,

Christian

**Comment by Jpadilla1** [comment]
Just tested on react-native 0.24.1 & 0.25.1 and the ChartsExplorer worked fine for me.

 React Native 0.24.1
<img width="487" alt="screen shot 2016-05-21 at 12 32 32 am" src="https://cloud.githubusercontent.com/assets/3780146/15446418/7ad4b6e6-1eee-11e6-8c46-5f35c0105ec6.png">

React Native 0.25.1
<img width="487" alt="screen shot 2016-05-21 at 12 54 16 am" src="https://cloud.githubusercontent.com/assets/3780146/15446420/8f8c3fbe-1eee-11e6-93c3-b8d3f7f475cb.png">
