### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by richfisher** [Jpadilla1/react-native-ios-charts#29]
following the Installation Instruction, and then run `react-native run-ios` and I got the following errors. thanks

> /Users/xx/Projects/demo/node_modules/react-native-ios-charts/RNiOSCharts/PieRadarChartViewBaseExtension.swift:22:12: error: value of type 'JSON' has no member 'isExists'
>     if json["rotationEnabled"].isExists() {
>        ~~~~^~~~~~~~~~~~~~~~~~~ ~~~~~~~~
> /Users/xx/Projects/demo/node_modules/react-native-ios-charts/RNiOSCharts/PieRadarChartViewBaseExtension.swift:26:12: error: value of type 'JSON' has no member 'isExists'
>     if json["rotationAngle"].isExists() {
>        ~~~~^~~~~~~~~~~~~~~~~ ~~~~~~~~
> /Users/xx/Projects/demo/node_modules/react-native-ios-charts/RNiOSCharts/PieRadarChartViewBaseExtension.swift:30:12: error: value of type 'JSON' has no member 'isExists'
>     if json["rotationWithTwoFingers"].isExists() {
>        ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~
> /Users/xx/Projects/demo/node_modules/react-native-ios-charts/RNiOSCharts/PieRadarChartViewBaseExtension.swift:34:12: error: value of type 'JSON' has no member 'isExists'
>     if json["minOffset"].isExists() {
>        ~~~~^~~~~~~~~~~~~ ~~~~~~~~

**Comment by Jpadilla1** [comment]
Hi! Which version of SwiftyJson do you have installed? It should be `2.3.1` without the `~>` in front.

**Comment by richfisher** [comment]
my Podfile is 

```
use_frameworks!

target 'MyApp' do
  pod 'SwiftyJSON', '2.3.1'
  pod 'Charts', '2.2.3'
end
```

**Comment by richfisher** [comment]
Environments:
OS X: 10.11
Xcode: 7.3.1
react-native: 0.24.1

Install steps:
Setting The minimum deployment target toiOS 8.0
1. Run npm install --save react-native-ios-charts
2. Add all the files under node_modules/react-native-ios-charts/RNiOSCharts.
3. When you add the files XCode should prompt you to create a bridging header if you haven't done so already. Create it and import the RCTViewManager.h. 
4. Just add a Podfile to your ios directory with the following content. Then run pod install and open the generated .xcworkspace from now on in xcode.
7. In your project's build settings, go to build options and change the Embedded Content Contains Swift Code to Yes.

**Comment by Jpadilla1** [comment]
hmm that error `error: value of type 'JSON' has no member 'isExists'` is normally caused by the new SwiftyJSON version that doesn't the `isExists` function anymore.
