### ISSUE TITLE
Issue on RN 26

### ISSUE THREAD

**Issue by Elyx0** [Jpadilla1/react-native-ios-charts#30]
I had to use codemod to update components/ and utils/ to the latest syntax, removing the errors.

``` js
import React, { Component } from 'react';
import { Text, StyleSheet, View } from 'react-native';
import { BarChart } from 'react-native-ios-charts';

export default class ChartsView extends Component {
  constructor(props) {
    super(props);
  }
  render(){
    return (
      <View style={styles.container}>
        <Text>Hello</Text>
        <BarChart
          config={{
            dataSets: [{
              values: [1, 2, 3, 10],
              colors: ['green'],
              label: '2015',
            }, {
              values: [3, 2, 1, 5],
              colors: ['red'],
              label: '2014',
            }],
            labels: ['a', 'b', 'c', 'd'],
          }}
          style={styles.chart}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    // borderWidth: 0,
    // borderColor: 'red',
    flex: 1,
    marginTop: 60,//cssConfig.header.height,
    justifyContent: 'flex-start',
    alignItems: 'center',
    // padding:0,
    backgroundColor: '#fafafa',
  },
  chart: {
    width: 200,
    height: 200
  }
});
```

![screenshot 2016-05-26 10 18 01](https://cloud.githubusercontent.com/assets/706218/15577629/4fb98eb4-232b-11e6-9e32-c8836b210e4d.png)

And in the console I get a lot of errors, I think I missed something in the Xcode part, it didn't ask me to create a bridge when adding the files.

Instead I get:

![screenshot 2016-05-26 10 18 22](https://cloud.githubusercontent.com/assets/706218/15577655/6a45ea20-232b-11e6-93b1-b13dfe12b0ad.png)

Any ideas ?

**Comment by Jpadilla1** [comment]
Hello! Looks like you are missing the bridge header file. For example, this is the header file on the latest version `0.2.5` for the ChartsExplorer https://github.com/Jpadilla1/react-native-ios-charts/blob/master/examples/ChartsExplorer/ios/ChartsExplorer-Bridging-Header.h . Check [here](http://stackoverflow.com/questions/31716413/xcode-not-automatically-creating-bridging-header) to add the reference to your project in XCode.

**Comment by Elyx0** [comment]
Exactly, i was misunderstanding because there was already a file named bridge in the lot. Removing and re-adding finally made the Xcode popup for a bridge file show, thanks.
