### ISSUE TITLE
Where do I add the chart files to?

### ISSUE THREAD

**Issue by ggaabe** [Jpadilla1/react-native-ios-charts#32]
Hi,

Hate to be a bother, but it isn't exactly clear where I add the chart files to in step 2. When I just add them straight under the Project directory (presumably in the xCode project under the ios folder), it doesn't prompt me to bridge the files at all.

Also, in step 3, which file do we import the `RCTViewManager.h` to?

**Comment by Jpadilla1** [comment]
Hey! Sorry that docs aren't clear enough, will work better on that when I get the chance. Have you checked this issue? https://github.com/Jpadilla1/react-native-ios-charts/issues/5 maybe that'll help.
