### ISSUE TITLE
has no member customAxisMin and customAxisMax

### ISSUE THREAD

**Issue by L-Jovi** [Jpadilla1/react-native-ios-charts#34]
list native chart and react native side version

`react-native-ios-charts`: `0.2.4`
`danielgindi/Charts`: `2.2.4`

I found some problem when I execute build.

![error](https://cloud.githubusercontent.com/assets/7262199/15885645/12a391ae-2d8b-11e6-8b25-7db955ea3f56.png)

how should I fix it?

thanks for your time :)

**Comment by Jpadilla1** [comment]
The issue is that for now you would have to use the Charts version `2.2.3` and freeze it like so.

```
use_frameworks!

target 'MyApp' do
  pod 'SwiftyJSON', '2.3.1'
  pod 'Charts', '2.2.3'
end
```

**Comment by L-Jovi** [comment]
@Jpadilla1  thanks for your reply, I close this issue and referenced it to [here](https://github.com/Jpadilla1/react-native-ios-charts/issues/35).
