### ISSUE TITLE
strange pod version incorrect

### ISSUE THREAD

**Issue by L-Jovi** [Jpadilla1/react-native-ios-charts#35]
hi, would you mind take a look [stackoverflow](http://stackoverflow.com/questions/37696803/pod-cant-specify-version-well)

I could't handle [this issue](https://github.com/Jpadilla1/react-native-ios-charts/issues/34) because strange pod install version.

thanks for your patience :)

**Comment by Jpadilla1** [comment]
Hey, were you able to solve your issue?

**Comment by L-Jovi** [comment]
no, I try many ways but failed :(

I'll try post the issue to **CocoaPods** ..
