### ISSUE TITLE
change barchart bar width

### ISSUE THREAD

**Issue by L-Jovi** [Jpadilla1/react-native-ios-charts#39]
hi, how should change `<BarChart>` bar width, I use `lineWidth` but failed.

thanks for your time :)

**Comment by Jpadilla1** [comment]
I think for that you would have to define a custom renderer or BarChart class from the swift library itself. Doesn't seem like their is a property that you set a value to at the moment.

**Comment by L-Jovi** [comment]
thanks for your idea, I'll try it :)
