### ISSUE TITLE
Customizing the Interaction with the Charts

### ISSUE THREAD

**Issue by hshim** [Jpadilla1/react-native-ios-charts#4]
It'd be nice to customize the touch interactions.
The original ios-charts project seems to support it.
(https://github.com/PhilJay/MPAndroidChart/wiki/Interaction-with-the-Chart) assuming that ios-charts has implemented these MPAndroidChart interaction features.

**Comment by Jpadilla1** [comment]
Hi! Yes I have plans to add them very soon. Maybe this week. I wanted to refactor the current charts first to use extensions which I got working today https://github.com/Jpadilla1/react-native-ios-charts/commit/f27834d294432a727f53424e255735dbae37dc8c

**Comment by Jpadilla1** [comment]
I added the interaction properties that are documented in that link. Let me know if this solves the issue!

**Comment by hshim** [comment]
Nice! Thanks for the update!

**Comment by minggo** [comment]
But how about the call back?

**Comment by SafiMohammed** [comment]
Can I use any callback function on clicking the charts?
