### ISSUE TITLE
red square and no chart appearing

### ISSUE THREAD

**Issue by aliouchka** [Jpadilla1/react-native-ios-charts#40]
hi, i've done all the installation instructions but nothing appears, only a red square around the zone where the chart is supposed to be, any idea of what the problem can be ?
thx :)

**Comment by OldTiger** [comment]
how do you fix it? I meet same problem

**Comment by EngineerDiab** [comment]
@aliouchka Im having the same problem? what did you do to fix it?

**Comment by rmevans9** [comment]
@OldTiger @EngineerDiab I resolved this issue by making sure the files from this project ended up in the "Compile Sources" section of the projects build settings. Away from my computer otherwise I would be more specific but simply adding the files there made things work for me.
