### ISSUE TITLE
Value of optional type 'RCTBridge?' not unwrapped; did you mean to use '!' or '?'?

### ISSUE THREAD

**Issue by mahlon-gumbs** [Jpadilla1/react-native-ios-charts#42]
Hi there.

I'm getting this error in the following files using react-native 0.28 and react-native-iso-charts 0.2.5:

node_modules/react-native-ios-charts/RNiOSCharts/RNBarChartManager.swift
node_modules/react-native-ios-charts/RNiOSCharts/RNScatterChartManager.swift
node_modules/react-native-ios-charts/RNiOSCharts/RNCandleChartManager.swift
node_modules/react-native-ios-charts/RNiOSCharts/RNLineChartManager.swift

I get past it by allowing Xcode to "fix it" which does adds a force unwrap. Problem is all of our developers have to do this the first time they build the app. Perhaps the module can be updated?

**Comment by Jpadilla1** [comment]
Just merged your PR, thanks!

**Comment by mahlon-gumbs** [comment]
Awesome. Thanks.

**Comment by wrousseau** [comment]
@Jpadilla1 Hi ! Could you make a new release with this fix please ?

**Comment by Jpadilla1** [comment]
@wrousseau just did a release! Sorry about that
