### ISSUE TITLE
Chart Zooms when clicked

### ISSUE THREAD

**Issue by EngineerDiab** [Jpadilla1/react-native-ios-charts#47]
At the moment when I click on the chart in the iOS simulator, the chart can zoom in infinitely. 

Is there a way to disable interaction with the chart. Or disable zooming specifically.

**Comment by Jpadilla1** [comment]
Did you try setting these props? https://github.com/Jpadilla1/react-native-ios-charts/blob/master/utils/commonProps.js#L141-L142

Sorry for not having documentation to make this clearer.

**Comment by EngineerDiab** [comment]
@Jpadilla1 

Thanks a ton, that's exactly it
