### ISSUE TITLE
How to remove values in the top axis of HorizontalBarChart

### ISSUE THREAD

**Issue by EngineerDiab** [Jpadilla1/react-native-ios-charts#48]
I'm having difficulty finding the prop. Sorry if this is an obvious question!

**Comment by Jpadilla1** [comment]
Did you try this one? https://github.com/Jpadilla1/react-native-ios-charts/blob/master/utils/commonProps.js#L193

**Comment by EngineerDiab** [comment]
@Jpadilla1 Thanks for putting up with me. That's exactly it

**Comment by Jpadilla1** [comment]
No worries! Happy to help!
