### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by Taakn** [Jpadilla1/react-native-ios-charts#5]
Hello,

I am getting the following error when trying to build on React Native 0.19:

```
** BUILD FAILED **

The following build commands failed:
    CompileSwift normal x86_64 /Users/[USER]/Project/ReactProject/node_modules/react-native-ios-charts/RNiOSCharts/Libraries/Charts/Classes/Charts/BubbleChartView.swift
    CompileSwift normal x86_64 /Users/[USER]/Project/ReactProject/node_modules/react-native-ios-charts/RNiOSCharts/Libraries/Charts/Classes/Charts/LineChartView.swift
    CompileSwift normal x86_64 /Users/[USER]/Project/ReactProject/node_modules/react-native-ios-charts/RNiOSCharts/Libraries/Charts/Classes/Components/ChartYAxis.swift
    CompileSwift normal x86_64 /Users/[USER]/Project/ReactProject/node_modules/react-native-ios-charts/RNiOSCharts/Libraries/SwiftyJSON/Tests/SequenceTypeTests.swift
    CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(5 failures)
Installing build/Build/Products/Debug-iphonesimulator/ReactProject.app
An error was encountered processing the command (domain=LaunchServicesError, code=0):
The operation couldn’t be completed. (LaunchServicesError error 0.)
Launching $(PRODUCT_BUNDLE_IDENTIFIER)

An error was encountered processing the command (domain=FBSOpenApplicationErrorDomain, code=4):
The operation couldn’t be completed. (FBSOpenApplicationErrorDomain error 4.)
```

Do you know what could be causing the issue ?

Thanks so much

**Comment by Jpadilla1** [comment]
Hello, I built a simple app using React Native 0.19 and I didn't have any problems.
What's your setup? So I can try to reproduce.

**Comment by Taakn** [comment]
I'm actually confused I think by your installation instruction:
- What do you mean by "Add all the files under node_modules/react-native-ios-charts/RNiOSCharts" ? Do you mean under the root project?
- When you say "Create it and import the RCTViewManager.h", how do I do that? When you say "#import "RCTViewManager.h"" where is it?
- When you say "install SwiftyJSON and iOS Charts"... How? It seems to me it's already included in your library.
- When you talk about "SwiftyJSON.framework and Charts.framework" I assume it's the one for iOS? There are multiple like for OSX or AppleTV

Thanks so much, I apologize I am a beginner in iOS/Xcode development and some of the instructions are not very clear to me

**Comment by Jpadilla1** [comment]
No need to apologize, I perfectly understand. I updated the npm version to reflect the latest changes. Try 0.0.8 and let me know if that works for you!
- What do you mean by "Add all the files under node_modules/react-native-ios-charts/RNiOSCharts" ? Do you mean under the root project? -> What I mean is to add them to your XCode project by right clicking in the left side bar where your files are 'Add files to <project/folder name>'.
- When you say "Create it and import the RCTViewManager.h", how do I do that? When you say "#import "RCTViewManager.h"" where is it? -> When you add the files, Xcode should prompt you to create that file and the only contents that file should have is "#import "RCTViewManager.h"
- When you say "install SwiftyJSON and iOS Charts"... How? It seems to me it's already included in your library. -> The easiest way is by using (Cocoapods)[https://cocoapods.org], you can install it running `gem install cocoapods`, create a file named Podfile under the iOS folder of your project and put the contents that are in the readme. Next run `pod install` in the folder. Once done, you will open the ProjectName.xcworkspace file from now on.
- When you talk about "SwiftyJSON.framework and Charts.framework" I assume it's the one for iOS? There are multiple like for OSX or AppleTV -> Yes, it's the one for iOS. If you use (Cocoapods)[https://cocoapods.org] you don't need to worry about this step.

**Comment by Taakn** [comment]
Thanks for your reply! "Unfortunately" with React Native a lot of people that have never ever done iOS development are going to be swarming the framework, so you might have to dumb things down a little bit :)
- For adding the file seems like it works. I created a new Group then added the files, initially I was adding the whole folder "RNiOSCharts" and it was not prompting me for the bridge header, but now it did (and added it under my Group). So I guess that's working.
- For the `pod install` portion, I am getting the following error, if that means something to you:

```
[!] Unable to satisfy the following requirements:

- `Charts (~> 2.2)` required by `Podfile`
- `Charts (~> 2.2)` required by `Podfile`

Specs satisfying the `Charts (~> 2.2)` dependency were found, but they required a higher minimum deployment target.

Specs satisfying the `Charts (~> 2.2)` dependency were found, but they required a higher minimum deployment target.
```

Thanks again for your help

**Comment by Jpadilla1** [comment]
Yeah, I can relate because the same thing happened to me. I'll try to make the installation process as simple as possible maybe by integrating (RNPM)[https://github.com/rnpm/rnpm] to make the linking process much simpler.

As for the `pod install`, you would need to set your project dependency target to be atleast iOS 8.0.

<img width="1392" alt="screen shot 2016-02-10 at 5 27 51 pm" src="https://cloud.githubusercontent.com/assets/3780146/12962424/a2a2617c-d01b-11e5-931d-40767e372079.png">

Then run `pod install` again.

**Comment by Taakn** [comment]
Okay it's working! Thanks a lot for your help and patience, I really appreciate it.

**Comment by Jpadilla1** [comment]
Happy to help!
