### ISSUE TITLE
Build Error - No such module 'Charts'

### ISSUE THREAD

**Issue by uriklar** [Jpadilla1/react-native-ios-charts#53]
Hi @Jpadilla1, 
I'm trying to install the library (v0.2.6). I'm running react-native v0.32.0. I've followed the installation instructions one by one, and when I try to run the project via the .xcworkspace file in Xcode, i'm getting the error:
`No such module 'Charts'`
In the file: `RNBubblrChart.swift`

I installed Charts and SwiftyJSON using Cocoapods

Any idea what the issue is? I'd be happy to provide any additional information needed.
Thanks!
Uri

**Comment by uriklar** [comment]
Ok, not sure exactly how I solved this, but it involved doing a pod reinstall. 
I used: https://github.com/CocoaPods/cocoapods-deintegrate to uninstall pods. 
I think it might of had something to do with another library I was installing using cocoapods which messed things up... 

I wasn't sure if I needed to add Charts and SwiftyJSON to the Link Binary With Libraries section. Right now, in the working setup, the Link Binary With Libraries section has the framework: `Pods_MyProjectName.framework`

Hope this helps someone in the future...

**Comment by tercanomer** [comment]
Either de-integrating and `run pods` helped or after doing that I re-opened the xcode project. This time I opened using the parent `ios` folder and not the `.xcodeproj` file inside it. 

Now I can see the `Pods` project in addition to my own project in project navigator and it compiles ok.
