### ISSUE TITLE
XCode 8 + Swift 2.3 / Swift 3 issues

### ISSUE THREAD

**Issue by laszlolm** [Jpadilla1/react-native-ios-charts#59]
Hi,
As I installed XCode 8 it asked me if I want to convert the files to the latest Swift version.
Regardless of what I say (Later / Convert) I get tons of exceptions from XCode (even XCode 7 doesn't work now, tried installing that one too). The exceptions look like this:
<img width="253" alt="screen shot 2016-09-21 at 1 17 16" src="https://cloud.githubusercontent.com/assets/7858366/18692267/52cea2a4-7f99-11e6-8607-6eb94e171027.png">
Of course there are many more exceptions under these (200+ / 600+ depending on if I chose to upgrade or not)
Does anyone have a solution for this if I just wanna use the old version from everything?

Thanks!

**Comment by mahlon-gumbs** [comment]
@noxowe did you resolve this? If so, how?

**Comment by williamhatsv** [comment]
@noxowe This issue was closed by yourself. Do you have the solution? If yes, can you post it here.
