### ISSUE TITLE
Error node-gyp with bufferutil@1.2.1 

### ISSUE THREAD

**Issue by Taakn** [Jpadilla1/react-native-ios-charts#7]
Hello,

I am getting the following error with RN 0.20. I know this is not an error with your component but with a dependency. I looked online for solutions but couldn't find any that worked. Have you encountered this issue before? Do you know what could be causing it?

Thanks so much

```
$ npm install --save react-native-ios-charts

> bufferutil@1.2.1 install /Users/user/Hive/Hive/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/bufferutil.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/user/Hive/Hive/node_modules/bufferutil
gyp ERR! node -v v5.3.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN install:bufferutil@1.2.1 bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN install:bufferutil@1.2.1 Exit status 1
Hive@0.0.1 /Users/user/Hive/Hive
└── react-native-ios-charts@0.0.8 
```

**Comment by Jpadilla1** [comment]
Hi! I've never had this issue before and I installed the package on RN 0.20 and it worked just fine for me. Not sure if it's a `node` or `npm` version issue. Currently, I've been using `node` v4.0.0 and `npm` 2.14.2 and I have not had any issues.

**Comment by Taakn** [comment]
Ok thanks so much. I'm going to close the issue since this is most likely not related to your component. I'll post the fix here when I find it so people running into the same issue find a solution. I am using `node` 5.3.0 and `npm` 3.3.12

Thanks again!

**Comment by Taakn** [comment]
@Jpadilla1 actually that error was solved by updating El Capitan but it was apparently unrelated to the library not working.

When I am trying to run `react-native run-ios`, the app starts but then it shuts down. I do not get any errors in Chrome debugging. Do you know what could be causing this issue?

Thanks so much
