### ISSUE TITLE
Swift compliler Errors

### ISSUE THREAD

**Issue by CarmeloXue** [Jpadilla1/react-native-ios-charts#79]
I'm a starter in this area and i try to run example but got this pills of errors 

![image](https://cloud.githubusercontent.com/assets/24514156/22196024/13d129b0-e186-11e6-80c1-a7d52192fbc3.png)

swiftJson 2.3.2
charts 3.0.1

**Comment by CarmeloXue** [comment]
still i have 4 errors 

![image](https://cloud.githubusercontent.com/assets/24514156/22197778/7bd27228-e18e-11e6-87b4-23bc44036867.png)


both of my chart and swiftjson  is 3.0.0

**Comment by reformer** [comment]
Im also sad on swift version up-gradation. No clue how to resolve this large number of errors.

**Comment by CarmeloXue** [comment]
@reformer now i just adjust my swfit to 3.0.0 and get the fork branch,but still had 3 or 4 errors. And the version conflicts still remain to be solved

**Comment by reformer** [comment]
@CarmeloXue do you got solution ?

**Comment by CarmeloXue** [comment]
@reformer no solution yet

**Comment by wuxudong** [comment]
I fork this repo, and update Charts to newest version V3.  you can check it at 
https://github.com/wuxudong/react-native-ios-charts

I have no experience of coding with swift & oc, so I can only fix compile error based on google and xcode hint. It took me hours.

It seems work.

btw: there is lot code duplications in this repo.  need to be refactor.

**Comment by wuxudong** [comment]
there is some breaking change between Charts v2 and v3. 

check examples->ChartsExplorer->components->TimeSeriesLine to get more info

**Comment by reformer** [comment]
@wuxudong There is lots of chances made in v3. I seen datasource provide to chart is now changed then callback methods too. So i think its take time to write whole lib. But now i doing one idea i complied and run V3 lib in native and i start writing my own wrapper around charts which i wanted. BTW take your time for refactoring your code. I have also plan in future to share my work here.

**Comment by CarmeloXue** [comment]
@wuxudong I got your solution, add all the files and RCTViewManager, pod install done, but still got this 

![image](https://cloud.githubusercontent.com/assets/24514156/23401402/86a96b96-fde2-11e6-8595-db13ef58c5e4.png)

and my project is like this 

![image](https://cloud.githubusercontent.com/assets/24514156/23401420/97200e8a-fde2-11e6-9c54-b676e1401f2d.png)

**Comment by CarmeloXue** [comment]
@wuxudong never mind. Problem has solved

**Comment by reformer** [comment]
@CarmeloXue have you convert all lib in latest version swift 3.0 in react native?

**Comment by CarmeloXue** [comment]
![image](https://cloud.githubusercontent.com/assets/24514156/23402919/a3670db4-fde8-11e6-8dd1-ae8ec4b14b0e.png)

now when i try to run a demo, got this error

**Comment by reformer** [comment]
@CarmeloXue You not able to properly integrate chart lib in your project. Chart lib swift 3.0 is properly compile  using pod dependency but when you trying to use bridge classes between chart lib and react native then it give errors. In Your case after since your screenshot you not adding those bridge classes from node modules. You must add those classes in your XCode if all going good then your all error gone. That's why i created my own bridge wrapper sync with latest lib.

**Comment by CarmeloXue** [comment]
@reformer tried to add these to framework to and add it

![image](https://cloud.githubusercontent.com/assets/24514156/23443855/8b7cd588-fe6c-11e6-81d4-75257bbb021d.png)

and add 

![image](https://cloud.githubusercontent.com/assets/24514156/23443873/ac70b926-fe6c-11e6-9d8d-04de245e956f.png)

all these files under node-module, but still got Native component not found error. I don't know anything about Xcode or OC or swift，and i don't know if i add the bridge correct

**Comment by CarmeloXue** [comment]
@reformer problem solved, i just change the content of my bridging-header to 
#import <React/RCTViewManager.h>
#import <React/RCTUIManager.h>
and the problem solved. 
I try to remove #import <React/RCTUIManager.h> , and the errors show. So i think the problem may cause by it. But still dont know why...BTW  many thx

**Comment by reformer** [comment]
@CarmeloXue Congratulation!. If you don't mind share your work to other whomsoever in trouble,

**Comment by wuxudong** [comment]
Is it solved now?

I am working on a new repo, try to merge this ios version with another android version. It is almost done.

**Comment by reformer** [comment]
@wuxudong  yes according to your screenshot it seems to solve. Try to use one of example using latest version of graph.

**Comment by CarmeloXue** [comment]
thx both of you!

**Comment by wuxudong** [comment]
@reformer Actually I am also new to xcode, I got a problem to extract it as a library. 

In react-native-ios-charts installation guide, you need to copy source files to your own project.  
Maybe react-native link is better.

I want to extract this as a standalone cocoa-touch-framework. 
But after I moved these ui component codes to an standalone xcode project, I can not get it compiled successfully.

the detail is described at [here](http://stackoverflow.com/questions/42546995/how-to-create-native-ios-react-native-module), can you help?

**Comment by wuxudong** [comment]
Finally. check this. 
https://github.com/wuxudong/react-native-charts-wrapper

**Comment by reformer** [comment]
@wuxudong  Thanks a lot dude :)
