### ISSUE TITLE
setting config 'colors' broken

### ISSUE THREAD

**Issue by brycepavey** [Jpadilla1/react-native-ios-charts#8]
Hey there, I've been attempting to set the colors on both a line chart and pie chart but both crash the app.
I attempted this on react-native 0.21, but I've now discovered colorProcessing was reimplemented in 0.21 and no longer supports arrays of colors (https://github.com/facebook/react-native/commit/c8a0a3eff6e18b21feb89cfdd3a375adab6a68e2)

Though I rolled back to both 0.20 and 0.19 and both give same error, I'm unsure if this is something of my own doing or a issue with this library. I tried using the sample code from the readme and produced the same results, regardless here is my render code to produce the error.

``` JavaScript
<View style={styles.container}>
        <View style={{ marginTop: 50, flexDirection: 'row'}}>
          <LineChart
            config={{
              dataSets: [{
                values: [1, 2, 3, 10, 3, 2, 1, 5, 13, 10, 11, 14, 2, 5, 1, 5, 12, 19, 12],
                colors: ['red'],
                drawValues: false,
                drawFilled: true,
                circleRadius: 3,
                drawHorizontalHighlightIndicator: false,
                drawVerticalHighlightIndicator: false,
              }],
              labels: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n'],
              showLegend: false,
              xAxis: {enabled: false},
              leftAxis: { enabled: false},
              rightAxis: { enabled: false},
              animation: {  xAxisDuration: 1,
                            yAxisDuration: 1,
                            easingOption: 'easeOutExpo'},
              scaleYEnabled: false,
            }}
            style={styles.chart}
          />
        </View>
 </View>
```

Here's where it crashes in RNLineChart.swift

![screen shot 2016-03-04 at 3 42 57 pm](https://cloud.githubusercontent.com/assets/6986339/13518378/11c46962-e221-11e5-868f-4c9dd1573fc3.png)

**Comment by Jpadilla1** [comment]
Hey there! Can you try installing from source and see if that works for you? I made the changes in this commit https://github.com/Jpadilla1/react-native-ios-charts/commit/e2c358e9d6b798a20006c11e814437c3cad71650 a while back and it seems to work for me. Let me know so I can make any fix and do a release.

Thanks!

**Comment by brycepavey** [comment]
Sure thing, I'll give it a shot now and report back!

**Comment by brycepavey** [comment]
That did it, thanks!
I noticed when I was installing via npm the other day that the ChartViewBaseExtension.swift wasn't up to date with that commit, so I replaced the whole RNiOSCharts folder from source. I overlooked the changes to utils/commonColorProps.js from that commit though. I just compared the version I had and it doesn't contain those changes, so the version I got from npm is listed as v0.0.8 but seems to be a previous release :confused:

**Comment by Jpadilla1** [comment]
Glad to here! I'll be doing a release soon (probably tomorrow) to address this issue. I'll let you know.

**Comment by Jpadilla1** [comment]
Hey I just made a release with those changes. It should be on npm, version `0.0.9`

**Comment by brycepavey** [comment]
Awesome! Thanks for this library!
