### ISSUE TITLE
Support for CandleStick Chart

### ISSUE THREAD

**Issue by BilalBudhani** [Jpadilla1/react-native-ios-charts#9]
In my current project I've requirement to use CandleStick chart in react native. I looked into your other charts implementation and tried working on CandleStick Chart support myself. But, my lack of iOS knowledge led to failure. Do you have any plans to add support for this chart anytime soon? If not, I'm open to take this on me and try again if I could get some guidance.

**Comment by Jpadilla1** [comment]
Hello! Yes, I have plans to support most or all the iOS-charts libraries features including the CandleStick graph. Unfortunately, I've been busy for while now and it could take sometime for me to include support for the candle stick. I'm happy to make a contribution guide so it'll help you and hopefully other devs to contribute to the library! I'll try to get something out this week and let you know.

**Comment by Jpadilla1** [comment]
Hey @BilalBudhani, I added support for the CandleStick Chart in the latest version. I also added Bubble, Scatter and Radar charts. Let me know if that works for you! With example code in the readme.

**Comment by BilalBudhani** [comment]
@jpadilla1 Awesome! Thank you so much for adding CandleStick Chart support so quickly. I'll check it out and try to integrate it.

**Comment by Jpadilla1** [comment]
@BilalBudhani Yes, it was really simple since I started using extensions in swift :)

**Comment by masterkrang** [comment]
@Jpadilla1 can I include volume along with the candlestick charts like in android? cc @BilalBudhani 
Example: 
![image](https://cloud.githubusercontent.com/assets/452219/14090644/64c74300-f4f0-11e5-91ca-910c49d3aa88.png)

**Comment by Jpadilla1** [comment]
@masterkrang You might be able to do so by using the CombinedChart. See this issue on the MPAndroidChart library https://github.com/PhilJay/MPAndroidChart/issues/969
